<?php

require_once '../../panel/init.php';
require_once '../whmcs/connect.php';

$productAll = product();

?>
<div class="upload">
    <form action="add.php" method="post" enctype="multipart/form-data">
        Selectionner les tailles :
        <select id="selectImageSneakers" name="pid">
            <option value> Chaussure Selectionné</option>
            <?php foreach ($productAll['product'] as $product) { ?>
                <option value="<?= $product['pid'] ?>"> <?= $product['name'] ?></option>
            <?php } ?>
        </select>

        <div id="nbListe">
            <input type="hidden" name="nbListe" value="0">
        </div>

        <table id="newTaille">

                <tr>
                    <th>
                        <label for="taille0">Taille:</label>
                    </th>
                    <th>

                        <label for="qtn0">Quantite:</label>
                    </th>
                </tr>

                <tr id="input0">
                    <td>
                        <input type="number" id="taille" name="size0" oninput="addTaille(0)"/>
                    </td>
                    <td>
                        <input type="number" id="qtn" name="count0" oninput="addTaille(0)"/>
                    </td>
                </tr>

        </table>

        <input class="btn btn-danger" type="submit" value="Upload Size" name="submit">
    </form>
</div>

<script>
    var listTaille = document.getElementById("newTaille");
    var divNumber = document.getElementById("nbListe");
    var nbListe = 1;

    function addTaille(nbInput) {
        // listTaille.innerHTML = '<input type="hidden" name="nbListe" value="' + nbListe + '"> <li><label for="taille' + nbListe + '">Taille:</label><input type="number" id="taille' + nbListe + '" name="size' + nbListe + '" /></li><li><label for="qtn' + nbListe + '">Quantite:</label><input type="number" id="qtn' + nbListe + '" name="count' + nbListe + '" /></li>';

        console.log(nbListe, nbInput+1);
        if (nbListe !== nbInput+1){
            console.log("form add old")
        } else {
            var nouvelDiv = document.createElement("tr");
            nouvelDiv.id = "input" + nbListe;
            nouvelDiv.innerHTML = ' <td> <input type="number" id="taille" name="size'+ nbListe +'" oninput="addTaille('+ nbListe +')"/> </td> <td> <input type="number" id="qtn" name="count'+ nbListe +'" oninput="addTaille('+ nbListe +')"/> </td>';

            listTaille.appendChild(nouvelDiv);

            var nbHidden = nbListe-1;
            divNumber.innerHTML = '<input type="hidden" name="nbListe" value="'+ nbHidden +'">'

            nbListe++;
        }
    }
</script>

<style>
    body{
        background-color: #E6E6E6
    }
    .upload {
        background-color: #E6E6E6;
        width: 100%;
        margin: auto;
        padding: 30px;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    button,
    input,
    optgroup,
    select,
    textarea {
        margin: 5px;
    }

    .btn {
        margin-top: 30px;
    }
    th{
        padding: 4px;
        font-weight: 700;
        background-color: #bb2d3b;
        border-bottom: 1px solid #ddd;
        border-radius: 3px;
        text-align: center;
        color: #fff;
    }
    td{
        background-color: #ffbdbd;
    }
</style>