<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


<?php

require_once '../../panel/init.php';
require_once '../whmcs/connect.php';

$productAll = product();

?>
<div class="upload">
    <form action="add.php" method="post" enctype="multipart/form-data">
        Selectionner les tailles :
        <select id="selectImageSneakers" name="pid">
            <option value> Chaussure Selectionné</option>
            <?php foreach ($productAll['product'] as $product) { ?>
                <option value="<?= $product['pid'] ?>"> <?= $product['name'] ?></option>
            <?php } ?>
        </select>




        <input class="btn btn-danger" type="submit" value="Upload Size" name="submit">
    </form>
</div>

<script>



</script>