<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">


  <!-- Section: Links  -->
  <section>
    <div class="container text-center text-md-start pt-3">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Nom de l'entreprise
          </h6>
          <p>
            Fondée en 2021 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur, accusamus perspiciatis harum possimus quos ad eligendi qui, non impedit atque rerum reiciendis sit
          </p>
        </div>
        <!-- Grid column -->

        <!-- PAGE -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 text-center">
          <h6 class="text-uppercase fw-bold mb-4">Page</h6>
          <p>
            <a href="products.php" class="text-reset">Sneakers</a>
          </p>
          <p>
            <a href="nettoyage.php" class="text-reset">Nettoyage</a>
          </p>
          <p>
            <a href="actu.php" class="text-reset">Actualité</a>
          </p>
        </div>
        <!-- / PAGE -->

        <!-- MEINTION -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 text-center">
          <h6 class="text-uppercase fw-bold mb-4">Mentions</h6>
          <p>
            <a href="#!" class="text-reset">Connexion</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Panier</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Termes d'utilisation</a>
          </p>
          <p>
            <a href="#!" class="text-reset">CMS WHMC</a>
          </p>
        </div>
        <!-- / MENTION-->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-4 mx-auto mb-md-0 mb-4">
        <h6 class="text-uppercase fw-bold mb-4">A propos de nous</h6>
          <p>
            <i class="fas fa-envelope me-3"></i>
            palaisdelasneaks@gmail.com</p>
          <p><i class="fas fa-phone me-3"></i>06.51.72.66.93</p>
          <p><i class="fa-solid fa-house"></i>52 boulevard des castors 69005 Lyon</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Palais De la Sneaks <br/></a>
    Created by : Tyrolium
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->