<div style="height: 70px"></div>

<nav id="nav-desktop" class="fixed-top">
    <div class="row">

        <div class="logo col-3">
            <a class="navbar-brand" href="/">
                <img src="assets/logoDetoure.png" alt="Logo" class="d-inline-block align-text-top">
                Palais de la sneaks
            </a>
        </div>
        <ul class="col-6">
            <li><a href="index.php">Accueil</a></li>
            <li>
                <a href="products.php">Sneakers</a>
            </li>
            <li><a href="nettoyage.php">Nettoyage</a></li>
            <li><a href="panel/index.php?rp=/announcements">Actualité</a></li>
            <li><a href="rachat.php">Rachat</a></li>

        </ul>
        <ul class="col-2 endNavbar">

            <a href="panel/cart.php?a=view" class="panier">
                <i class="fa-solid fa-basket-shopping"></i>
            </a>

            <?php

            require_once './panel/init.php';

            ?>

                <div class="connexion">
                <a href="panel/clientarea.php"><button class="custom-btn btn-7"> <span>Espace client</span>   </button></a>
  
                </div>
        </ul>
    </div>
</nav>

<?php // var_dump($_SESSION); 
?>

<!--Navbar-->
<header id="nav-mobile">


    <a href="panel/cart.php?a=view" class="panier panierMobile">
        <i class="fa-solid fa-basket-shopping"></i>
    </a>

    <h1><a href="./" class="titleMobile"><img class="img-mobile" src="assets/logoDetoure.png">Palais de la sneaks</a></h1>

    <input id="burger" type="checkbox" />


    <label for="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>

    <nav>
        <ul>
            <li><a href="index.php">Accueil</a></li>
            <li><a href="products.php">Sneakers</a></li>
            <li><a href="nettoyage.php">Nettoyage</a></li>
            <li><a href="panel/index.php?rp=/announcements">Actualité</a></li>
            <li><a href="rachat.php">Rachat</a></li>

            <li><?php


                require_once 'panel/init.php';


                if ($_SESSION['login_auth_tk']) {
                    $isLog = true;

                    $firstName = $_SESSION['cart']['user']['firstname']; ?>

                    <div class="frame">
                        <a href="panel/clientarea.php"><button class="custom-btn btn-7"><span> Profil </span> </button></a>
                    </div>

                <?php
                } else {
                    $isLog = false;

                    echo '
                    <div class="connexion">
                    <a href="panel/clientarea.php"><button class="custom-btn btn-7"><span>Espace client</span>   </button></a>
    
                    </div>';
                }


                ?>
            </li>
        </ul>
    </nav>
</header>