<div style="height: 70px"></div>

<nav class="fixed-top">
    <div class="row">

        <div class="logo col-3">Le Palais De La Sneaks</div>
        <ul class="col-6">
            <li><a href="index.php">Accueil</a></li>
            <li>
                <a href="products.php">Sneakers</a>
                <ul>
                    <li><a href="products.php"></a>Adidas</li>
                    <li><a href="products.php"></a>Nike</li>
                    <li><a href="products.php"></a>Jordan</li>
                    <li><a href="products.php"></a>Yeezy</li>
                </ul>
            </li>
            <li><a href="nettoyage.php">Nettoyage</a></li>
            <li><a href="actu.php">Actualité</a></li>
        </ul>
        <ul class="col-2 connexion">
        <a href="panel/clientarea.php" type="button" class="btn btn-danger">Se connecter</a>
        </ul>
      
    </div>
</nav>

<style>

    nav{
        border: 2px solid rgba(0, 0, 0, 0.30);
        background: #FFF;
        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
    }

    nav ul{
        margin-bottom: unset;
    }


</style>