<div style="height: 70px"></div>

<nav id="nav-desktop" class="fixed-top">
    <div class="row">

        <div class="logo col-3">
            <a class="navbar-brand" href="#">
                <img src="app/assets/logoDetoure.png" alt="Logo" class="d-inline-block align-text-top">
                Palais de la sneaks
            </a>
        </div>
        <ul class="col-6">
            <li><a href="index.php">Accueil</a></li>
            <li>
                <a href="products.php">Sneakers</a>
            </li>
            <li><a href="nettoyage.php">Nettoyage</a></li>
            <li><a href="panel/index.php?rp=/announcements">Actualité</a></li>
            <li><a href="rachat.php">Rachat</a></li>

        </ul>
        <ul class="col-2 connexion">

            <a href="panel/cart.php?a=view" class="panier">
                <i class="fa-solid fa-basket-shopping"></i>
            </a>

            <?php


            require_once './panel/init.php';


            if ($_SESSION['login_auth_tk']) {
                $isLog = true;

                $firstName = $_SESSION['cart']['user']['firstname']; ?>

                <a href="panel/clientarea.php" type="button" class="btn btn-danger">Profil <?php if ($firstName) {
                                                                                                echo $firstName;
                                                                                            } ?></a>

            <?php
            } else {
                $isLog = false;

                echo '<a href="panel/clientarea.php" type="button" class="btn btn-danger">Espace Client</a>';
            }


            ?>
        </ul>
    </div>
</nav>

<?php // var_dump($_SESSION); 
?>

<!--Navbar-->
<header id="nav-mobile">


    <a href="panel/cart.php?a=view" class="panier panierMobile">
        <i class="fa-solid fa-basket-shopping"></i>
    </a>

    <h1><a href="./" class="titleMobile"><img class="img-mobile" src="app/assets/logoDetoure.png">Palais de la sneaks</a></h1>

    <input id="burger" type="checkbox" />


    <label for="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>

    <nav>
        <ul>
            <li><a href="index.php">Accueil</a></li>
            <li><a href="products.php">Sneakers</a></li>
            <li><a href="nettoyage.php">Nettoyage</a></li>
            <li><a href="panel/index.php?rp=/announcements">Actualité</a></li>
            <li><a href="rachat.php">Rachat</a></li>

            <li><?php


                require_once 'panel/init.php';


                if ($_SESSION['login_auth_tk']) {
                    $isLog = true;

                    $firstName = $_SESSION['cart']['user']['firstname']; ?>

                    <a href="panel/clientarea.php" class="burger-btn-connect">Profil <?php if ($firstName) {
                                                                                            echo $firstName;
                                                                                        } ?></a>

                <?php
                } else {
                    $isLog = false;

                    echo '<a href="panel/clientarea.php" class="burger-btn-connect">Espace Client</a>';
                }


                ?>
            </li>
        </ul>
    </nav>
</header>