<?php
require_once 'panel/init.php';
require_once 'api/whmcs/connect.php';

$productAll = product();

?>


<main class="mainProductOne">
    <?php
    foreach ($productAll['product'] as $product) {
        if ($product['pid'] == $id) {
            $productPicture = getPicture($product['pid']); ?>
            <p id="hidd1" class="hidden"><?= $productPicture['picture1'] ?></p>
            <p id="hidd2" class="hidden"><?= $productPicture['picture2'] ?></p>
            <p id="hidd3" class="hidden"><?= $productPicture['picture3'] ?></p>

            <div class="main-container">
                <div class="images">
                    <div class="carrousel">
                        <button class="carrousel__previous buttonP" type="button" id="previousImg">
                            <img class="prev imgP" src="https://ainesc.github.io/product/images/icon-previous.svg" alt="Previous image" />
                        </button>
                        <img id="image" class="carrousel__img imgP" src="api/more/uploads/<?= $productPicture['picture1'] ?>" alt="" />
                        <button class="carrousel__next buttonP" type="button" id="nextImg">
                            <img class="next imgP" src="https://ainesc.github.io/product/images/icon-next.svg" alt="" />
                        </button>
                    </div>
                </div>
                <section aria-labelledby="product" class="product">
                    <h3 class="product__brand">NIKE</h3>
                    <h2 id="product" class="product__title">
                        <?= $product['name'] ?>
                    </h2>
                    <p class="product__description baliseP">
                        <?= $product['description'] ?>
                    </p>
                    <div class="product__price">
                        <div class="product__current">
                            <p class="product__current-price baliseP"><?= $product['pricing']['EUR']['monthly'] ?> €</p>
                            <!-- <span class="product__discount">50%</span> -->
                        </div>
                        <!-- <p class="product__former-price baliseP">$250.00</p> -->
                    </div>
                    <div class="cart">
                        <div class="cart__items">
                            <button onclick="removeQuantite()" type="button" id="less" class="cart__remove-item buttonP">
                                <i class="fa-solid fa-minus" style="color: #dc3545;"></i>
                            </button>
                            <p id="quantiteAdd" class="cart__current-items baliseP">0</p>
                            <button onclick="addQuantite()" type="button" id="more" class="cart__add-item buttonP">
                                <i class="fa-solid fa-plus" style="color: #dc3545;"></i>
                            </button>
                        </div>
                        <a id="addToCart" class="cart__button btn btnP btnP--primary">
                            Add to cart
                        </a>
                    </div>
                </section>
            </div>

    <?php }
    } ?>
    <script src="javascript/productOne.js"></script>
    <?php socialLink($page); ?>
</main>