<?php
require_once 'panel/init.php';
require_once 'api/whmcs/connect.php';

$productAll = product();

?>


<main>
    <?php
    foreach ($productAll['product'] as $product) {
        if ($product['pid'] == $id) { ?>
            <div class="product-card">
                <div class="product-image">
                    <img id="main-image" src="https://www.mimanerashop.com/images/nike-comics-red-rossa-cartoon-disegnato-a-mano-ros.1200x1200.11914.webp" alt="<?= $product['name'] ?>">
                </div>
                <div class="product-details">
                    <h1><?= $product['name'] ?></h1>
                    <br>
                    <p class="description"><?= $product['description'] ?></p>
                    <br>
                    <p class="price">Prix : <?= $product['pricing']['EUR']['monthly'] ?> €</p>
                    <a href="panel/cart.php?a=add&pid=<?= $product['pid'] ?>" class="buy-button">Acheter</a>
                </div>
                <div class="secondary-images">
                    <img class="secondary-image" src="https://www.mimanerashop.com/images/nike-comics.1200x1200.11917.webp" alt="Image 2">
                    <img class="secondary-image" src="https://www.mimanerashop.com/images/nike-comics.1200x1200.11919.webp" alt="Image 3">
                </div>
            </div>
    <?php }
    } ?>
</main>


