<h3 class="title">Rejoignez-nous !</h3>
<div id="sectionMedia">
    <div class="items">
        <div class="socialMedia">
        <i class="fa-brands fa-instagram"></i>
            <p>Rejoignez-nous sur Instagram pour découvrir des contenus exclusifs et inspirants au quotidien !</p>
            <button class="custom-btn btn-2" onclick="window.location.href = 'https://www.instagram.com/palais.de.la.sneaks/';">
                <i class="fa-solid fa-bell"></i>
                <span>Suivre</span>
            </button>
        </div>
    
        <div class="socialMedia">
        <i class="fa-brands fa-tiktok"></i>
            <p>Soyez au cœur de l'actualité en nous suivant sur TikTok, pour des informations de première main !</p>
            <button class="custom-btn btn-2" onclick="window.location.href = 'https://www.tiktok.com/@palais.de.la.sneaks';">
                <i class="fa-solid fa-bell"></i>
                <span>Suivre</span>
            </button>
        </div>
    </div>
</div>