<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


<form action="add.php" method="post" enctype="multipart/form-data">
    Select image to upload:
    <select name="pid">
        <option value> Chaussure Selectionné</option>
        <option value="1"> Premier Chaussure</option>
    </select>
    <input type="file" name="fileToUpload" id="fileToUpload">
<!--    <input type="file" name="fileToUpload1" id="fileToUpload">-->
<!--    <input type="file" name="fileToUpload2" id="fileToUpload">-->
    <input type="submit" value="Upload Image" name="submit">
</form>
